version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.app
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - app
    ports:
      - 80:80